# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoftwareDevelopmentProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoftwareDevelopmentProject

pod 'SideMenu'
pod 'IQKeyboardManagerSwift'
pod 'PopupDialog', '~> 1.1'
pod 'RangeSeekSlider'



end
